development:
  dialect: postgres
  database: blog
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: blog
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: blog
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  pool: 5
